version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: default-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'